# Generated by Django 4.1.5 on 2023-01-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('image', models.ImageField(upload_to='products/pictures/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'product picture',
                'verbose_name_plural': 'product pictures',
                'db_table': 'product_picture',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
                ('sub_attribute', models.ManyToManyField(related_name='parent_attribute', to='products.productattribute', verbose_name='sub_attribute')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
                'db_table': 'product_attribute',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='image')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='price')),
                ('stock', models.PositiveSmallIntegerField(default=0, verbose_name='stock')),
                ('attributes', models.ManyToManyField(related_name='products', to='products.productattribute', verbose_name='attributes')),
                ('categories', models.ManyToManyField(related_name='products', to='products.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
