# Generated by Django 4.1.5 on 2023-02-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productattribute_sub_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='off'),
        ),
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='price')),
                ('stock', models.PositiveSmallIntegerField(default=0, verbose_name='stock')),
                ('default_choice', models.BooleanField(default=False, verbose_name='default choice')),
                ('off', models.PositiveIntegerField(blank=True, null=True, verbose_name='off')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choices', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product choice',
                'verbose_name_plural': 'product choices',
                'db_table': 'product_choice',
                'unique_together': {('product', 'name')},
            },
        ),
    ]
