# Generated by Django 4.1.5 on 2023-02-06 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_off_productchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.category', verbose_name='parent category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent_category', 'title')},
        ),
    ]
