# Generated by Django 4.1.5 on 2023-02-06 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 6, 16, 3, 42, 35241, tzinfo=datetime.timezone.utc), verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 6, 16, 3, 53, 135154, tzinfo=datetime.timezone.utc), verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 16, 3, 24, 13673, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
