# Generated by Django 4.1.5 on 2023-02-09 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cart_user_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 12, 8, 8, 537948, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
