# Generated by Django 4.1.5 on 2023-02-16 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 7, 34, 28, 144467, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
