# Generated by Django 4.1.5 on 2023-03-20 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 6, 14, 10, 902389, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
