# Generated by Django 4.1.5 on 2023-03-22 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_description_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'top'), (1, 'high'), (2, 'normal'), (3, 'low')], default=2, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 5, 8, 53, 161584, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
