# Generated by Django 4.1.5 on 2023-05-05 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_picture_number_alter_cartitem_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 9, 6, 38, 870103, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
