# Generated by Django 4.1.5 on 2023-05-06 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 10, 10, 53, 666627, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
