# Generated by Django 4.1.5 on 2023-05-28 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_cartitem_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 6, 44, 23, 520475, tzinfo=datetime.timezone.utc), verbose_name='expire time'),
        ),
    ]
