# Generated by Django 4.1.5 on 2023-02-09 12:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_alter_cartitem_expire_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('status', models.PositiveIntegerField(choices=[(1, 'wait for payment'), (2, 'preparing to send'), (3, 'send shipment'), (4, 'delivered shipment'), (6, 'cancel')], default=1, verbose_name='status')),
                ('orders_price', models.PositiveBigIntegerField(default=0, verbose_name='order price')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'online'), (2, 'cash')], default=1, verbose_name='payment type')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2023, 2, 9, 13, 8, 8, 540590, tzinfo=datetime.timezone.utc))),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('phone_number', models.PositiveBigIntegerField(validators=[django.core.validators.RegexValidator('^989[0-3,9]\\d{8}$', 'Enter a valid phone number.', 'invalid')], verbose_name='phone number')),
                ('address', models.TextField(verbose_name='address')),
                ('postal_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='postal code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_information', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'delivery information',
                'verbose_name_plural': 'deliveries information',
                'db_table': 'delivery_information',
                'unique_together': {('address', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.PositiveIntegerField(auto_created=True, unique=True, verbose_name='tracking code')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('post_type', models.PositiveSmallIntegerField(choices=[(1, 'normal'), (2, 'fast')], default=1, verbose_name='post type')),
                ('send_cost', models.PositiveBigIntegerField(default=0, verbose_name='send cost')),
                ('delivery_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='orders.deliveryinformation', verbose_name='delivery information')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_send', to='orders.order')),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkout',
                'db_table': 'checkout',
            },
        ),
    ]
