# Generated by Django 4.1.5 on 2023-02-16 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='is open'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 16, 8, 34, 28, 147099, tzinfo=datetime.timezone.utc)),
        ),
    ]
