# Generated by Django 4.1.5 on 2023-05-05 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinformation',
            name='city',
            field=models.CharField(default='Tehran', max_length=32, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='state',
            field=models.CharField(default='Tehran', max_length=32, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 10, 6, 38, 872927, tzinfo=datetime.timezone.utc)),
        ),
    ]
