# Generated by Django 4.1.5 on 2023-06-02 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_checkout_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 9, 10, 3, 710318, tzinfo=datetime.timezone.utc)),
        ),
    ]
