# Generated by Django 4.1.5 on 2023-06-17 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 10, 28, 18, 664569, tzinfo=datetime.timezone.utc)),
        ),
    ]
