# Generated by Django 4.1.5 on 2023-07-07 07:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_expire_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliveryinformation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='phone_number',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Enter a valid phone number.', 'invalid')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 8, 55, 1, 45576, tzinfo=datetime.timezone.utc)),
        ),
    ]
