# Generated by Django 4.1.5 on 2023-07-07 07:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_deliveryinformation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'Enter a valid phone number.', 'invalid')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 8, 57, 57, 241304, tzinfo=datetime.timezone.utc)),
        ),
    ]
